# OpenStack modules
mod 'cinder',
  :git => 'https://git.openstack.org/openstack/puppet-cinder',
  :ref => 'stable/newton'

mod 'glance',
  :git => 'https://git.openstack.org/openstack/puppet-glance',
  :ref => 'stable/newton'

mod 'horizon',
  :git => 'https://git.openstack.org/openstack/puppet-horizon',
  :ref => 'stable/newton'

mod 'keystone',
  :git => 'https://git.openstack.org/openstack/puppet-keystone',
  :ref => 'stable/newton'

mod 'neutron',
  :git => 'https://git.openstack.org/openstack/puppet-neutron',
  :ref => 'stable/newton'

mod 'nova',
  :git => 'https://git.openstack.org/openstack/puppet-nova',
  :ref => 'stable/newton'

mod 'openstacklib',
  :git => 'https://git.openstack.org/openstack/puppet-openstacklib',
  :ref => 'stable/newton'

mod 'openstack_extras',
  :git => 'https://git.openstack.org/openstack/puppet-openstack_extras',
  :ref => 'stable/newton'

# External modules
mod 'apache',
  :git => 'https://github.com/puppetlabs/puppetlabs-apache',
  :branch => '1.10.0'

mod 'concat',
  :git => 'https://github.com/puppetlabs/puppetlabs-concat',
  :branch => '2.2.0'

mod 'inifile',
  :git => 'https://github.com/puppetlabs/puppetlabs-inifile',
  :branch => '1.6.0'

mod 'memcached',
  :git => 'https://github.com/saz/puppet-memcached',
  :tag => 'v2.8.1'

mod 'mysql',
  :git => 'https://github.com/puppetlabs/puppetlabs-mysql',
  :branch => '3.9.0'

mod "ntp",
  :git => "https://github.com/puppetlabs/puppetlabs-ntp.git",
  :ref => "4.1.x"

mod 'rabbitmq',
  :git => 'https://github.com/puppetlabs/puppetlabs-rabbitmq',
  :tag => '5.5.0'

mod 'staging',
  :git => 'https://github.com/nanliu/puppet-staging',
  :tag => '1.0.4'

mod 'stdlib',
  :git => 'https://github.com/puppetlabs/puppetlabs-stdlib',
  :branch => '4.12.0'

mod 'sysctl',
  :git => 'https://github.com/duritong/puppet-sysctl',
  :tag => 'v0.0.11'
