---
- name: Ensure centos-cloud repository is up to date
  hosts: all
  gather_facts: no
  tasks:
    - git:
        repo: "https://github.com/CentOS/centos-cloud"
        dest: "{{ source_location }}"
        update: "yes"
        force: "yes"
